
version: '3'
services:
  server:
    image: node:12.18.4
    working_dir: /code
    volumes:
      - type: bind
        source: ./server
        target: /code
  
  socket:
    image: node:12.18.4
    working_dir: /code
    volumes:
      - type: bind
        source: ./socket
        target: /code    

  db:
    image: mongo:latest
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - "dbdata:/var/lib/mongodb/data"
volumes:
  dbdata:

